Bugfix/not deletes underlying file
micro-elements/MicroElements.FileStorage pull request #24
Opened 2018-01-25 22:21 UTC by avgalex

The intermediate PR. It is necessary to add the test.

2018-01-26 05:49 UTC, petriashev requested changes
See notes

2018-01-26 05:49 UTC, petriashev commented on src/MicroElements.FileStorage/Abstractions/DeletedCollection.cs
> +        protected internal void DeleteKey(string key)
MarkAsDeleted

2018-01-26 05:49 UTC, petriashev commented on src/MicroElements.FileStorage/Abstractions/DeletedCollection.cs
> +        protected internal IEnumerable<string> GetDeletedKey()
GetDeletedKeys

2018-01-26 05:49 UTC, petriashev commented on src/MicroElements.FileStorage/Abstractions/DeletedCollection.cs
> +    public abstract class DeletedCollection
DelayedOperations

2018-01-26 05:49 UTC, petriashev commented on src/MicroElements.FileStorage/DocumentCollection.cs
> -    public class DocumentCollection<T> : IDocumentCollection<T> where T : class
Лучше инкапсулировать список во внутреннем поле

2018-01-26 16:37 UTC, avgalex commented on src/MicroElements.FileStorage/DocumentCollection.cs
> -    public class DocumentCollection<T> : IDocumentCollection<T> where T : class
Не совсем понял.
private protected что то не срабатывает.

2018-01-26 16:38 UTC, avgalex commented on src/MicroElements.FileStorage/Abstractions/DeletedCollection.cs
> +        protected internal void DeleteKey(string key)
Здесь именно удаляем ключ из списка помешанных для удаления.

2018-01-26 19:48 UTC, petriashev commented on src/MicroElements.FileStorage/Abstractions/DeletedCollection.cs
> +        protected internal void DeleteKey(string key)
По названию не понял. Ехал в метро.

2018-01-26 19:50 UTC, petriashev commented on src/MicroElements.FileStorage/DocumentCollection.cs
> -    public class DocumentCollection<T> : IDocumentCollection<T> where T : class
Комментарий к правой части) 
Я имею в виду, что лучше не через наследование сделать

2018-01-28 19:59 UTC, petriashev commented on src/MicroElements.FileStorage/DataStore.cs
> +                    var format = string.Format("{0}{1}", key, serializerInfo.Extension);
прикол в том, что это уже давно пофиксено)

2018-01-29 16:03 UTC, petriashev approved these changes

2018-01-29 16:03 UTC, merged